fixed error concerning 'TypeError: playerChoice() missing 1 required positional argument: 'numOfGames'' by adding arguments to all the necessary parameters